module Main where
--import ListExercise (callThem)
--import LearningList (workWithLists)
--import LearningFunctions (greetings)
--import LearningHigherOrderFunctions(call)
--import LearningPartialFunction(call)
--import LearningComposition(call)
--import LearningDatatypes(call)
--import FoldExercises(call)
--import LearningRecords(call)
--import LearningTypeclasses(call)
--import LearningMaybe(call)
import LearningIO(call)
main :: IO () 
main = call